/**
 * `whale-artifact` namespace dictionaries: the renderer copy for the office
 * artifact preview cards.
 */

/** Dictionary namespace owned by this plugin. */
export const NS = 'whale-artifact'

/** Simplified Chinese dictionary (the key-set source of truth). */
export const zh = {
  'artifact.createdBy': '由 Whale 生成',
  'artifact.open': '打开 {name}',
  'artifact.rows': '{count} 行',
  'artifact.slides': '{count} 页',
  'artifact.blocks': '{count} 节',
  'artifact.truncated': '预览已截断',
  'artifact.failed': '生成失败',
  'artifact.details': '详情预览',
}

/** English dictionary (same key set). */
export const en: Record<WhaleArtifactKey, string> = {
  'artifact.createdBy': 'Generated by Whale',
  'artifact.open': 'Open {name}',
  'artifact.rows': '{count} rows',
  'artifact.slides': '{count} slides',
  'artifact.blocks': '{count} blocks',
  'artifact.truncated': 'Preview truncated',
  'artifact.failed': 'Generation failed',
  'artifact.details': 'Preview details',
}

/** Union of this namespace's dictionary keys. */
export type WhaleArtifactKey = keyof typeof zh
